### PR TITLE
Miscellaneous fixes

### LINKED ISSUE #2: Resolving DNS servers
I think we should be reading the list of DNS servers from `/etc/resolv.conf` by default. WDYT? I'm thinking that it is painful to have to declare the DNS servers for each service.

### LINKED ISSUE #3: Requests are not cleaned up
The `requests` map within `AsyncDnsResolver` is not cleaned up supposing that UDP replies are lost (very common!). This will result in an OOM eventually.

### LINKED ISSUE #4: The DNS cache is not used
The cache isn't used for the purposes of lookup - the resolver only inserts into the cache.

### PR DESCRIPTION
**Pull request by huntc**
1. Now reads name servers from resolv.conf when configured.
2. Cleans up expired requests.
3. Utilises the cache when performing resolutions.
4. Fixed up the README with respect to these changes.
5. Fixed a previously broken test.

Fixes #2 
Fixes #3 
Fixes #4

### CODE REVIEW

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 1]
```diff
@@ -9,32 +11,35 @@ import ru.smslv.akka.dns.raw.{AAAARecord, ARecord, Answer, CNAMERecord, DnsClien
...
   private val negativeTtl = config.getDuration("negative-ttl", TimeUnit.MILLISECONDS)
   private val minPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
   private val maxPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
+  private val requestTtl = FiniteDuration(config.getDuration("request-ttl", TimeUnit.MILLISECONDS), TimeUnit.MILLISECONDS)
 
   private val random = new Random()
 
   private var requestId: Short = 0
-  private val requests = mutable.OpenHashMap[Short, CurrentRequest]()
+  private var requests = List.empty[(Short, CurrentRequest)]
```
Comment (huntc) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:41]: I changed the mutable map to an immutable list given that I believe it will offer better performance in the majority of situations, and also that we can rapidly scan elements in order to determine if they have expired.

File: src/main/resources/reference.conf [hunk 2]
```diff
@@ -24,6 +24,20 @@ akka {
...
+
+        # The IPs of nameservers to use e.g.
+        # akka.io.dns.async-dns {
+        #   nameservers = ["8.8.8.8", "8.8.4.4"]
+        # }
+        nameservers = []
+
+        # Whether to use the system's /etc/resolv.conf in place
+        # of nameservers
+        resolv-conf = off
```
Comment (viktorklang) [inline src/main/resources/reference.conf:36]: How about a path to a file instead of on/off?

File: src/main/resources/reference.conf [hunk 3]
```diff
@@ -24,6 +24,20 @@ akka {
...
+
+        # The time that a request is allowed to live before being discarded
+        # given no reply
+        request-ttl = 5s
```
Comment (viktorklang) [inline src/main/resources/reference.conf:41]: Can it be set to 0?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: Why List iso Vector?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 4]
```diff
@@ -43,36 +48,58 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
   private def nextId(): Short = {
     do {
       requestId = (requestId + 2).toShort
-    } while (requests.contains(requestId))
+    } while (requests.exists(_._1 == requestId))
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: Is this guaranteed to terminate?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 5]
```diff
@@ -43,36 +48,58 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
...
+        case None =>
+          val id = nextId()
+
+          requests =
+            requests.filter(_._2.expires.hasTimeLeft) :+
+              id -> CurrentRequest(sender(),
+                                   caseFoldedName,
+                                   None,
+                                   None,
+                                   Some(immutable.Seq.empty),
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: Nil?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 6]
```diff
@@ -9,32 +11,35 @@ import ru.smslv.akka.dns.raw.{AAAARecord, ARecord, Answer, CNAMERecord, DnsClien
...
+    systemNameServers.getOrElse(config.getStringList("nameservers").map(parseNameserverAddress)(breakOut))
   private val resolveIpv4 = config.getBoolean("resolve-ipv4")
   private val resolveIpv6 = config.getBoolean("resolve-ipv6")
   private val resolveSrv = config.getBoolean("resolve-srv")
   private val negativeTtl = config.getDuration("negative-ttl", TimeUnit.MILLISECONDS)
   private val minPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
   private val maxPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
+  private val requestTtl = FiniteDuration(config.getDuration("request-ttl", TimeUnit.MILLISECONDS), TimeUnit.MILLISECONDS)
 
   private val random = new Random()
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: Use ThreadLocalRandom if you don't need SecureRandom

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 7]
```diff
@@ -43,36 +48,58 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
...
+        case Some(answer) =>
+          sender() ! answer
+        case None =>
+          val id = nextId()
+
+          requests =
+            requests.filter(_._2.expires.hasTimeLeft) :+
+              id -> CurrentRequest(sender(),
+                                   caseFoldedName,
+                                   if (resolveIpv4) None else Some(immutable.Seq.empty),
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: Nil

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 8]
```diff
@@ -43,36 +48,58 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
...
+                                   if (resolveIpv6) None else Some(immutable.Seq.empty),
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: Nil

Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Also, Some(Nil) can be a cached instance instead of allocating new ones.

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 9]
```diff
@@ -97,34 +124,35 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
         Some(rrs.map(_.ttl).min * 1000L)
       }
 
-      requests.get(baseId) match {
-        case Some(req@CurrentRequest(client, name, None, _, None, currentTtl)) if (id & 1) == 0 =>
+      requests = requests.find(_._1 == baseId) match {
+        case Some((_, req@CurrentRequest(client, name, None, _, None, currentTtl, _))) if (id & 1) == 0 =>
           val canonicalName = resolveCanonicalName(name)
           val ttl = rrsMinTtl.map(math.min(currentTtl, _)).getOrElse(currentTtl)
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: `math.min(currentTtl, rrsMinTtl.getOrElse(currentTtl))`

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 10]
```diff
@@ -133,11 +161,12 @@ class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with
 
           cache.put(Dns.Resolved(name, ipv4, ipv6), ttl)
           client ! Dns.Resolved(name, ipv4, ipv6)
-          requests -= baseId
-        case Some(CurrentRequest(client, name, None, None, Some(srv), recordsTtl)) =>
+          requests.filterNot(_._1 == baseId)
+        case Some((_, CurrentRequest(client, name, None, None, Some(srv), recordsTtl, _))) =>
           client ! SrvResolved(name, srv)
-          requests -= baseId
+          requests.filterNot(_._1 == baseId)
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:171]: create a method for this operation, it's used in many places in the same file.

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 11]
```diff
@@ -154,4 +183,26 @@ object AsyncDnsResolver {
...
+  def parseSystemNameServers(resolvConf: File): Option[immutable.Seq[InetSocketAddress]] =
+    try {
+      val addresses =
+        for {
+          line <- Source.fromFile(resolvConf).getLines()
+          addr <- NameserverLine.findFirstMatchIn(line).map(_.group(1))
+        } yield parseNameserverAddress(addr)
+      Some(addresses.toList)
+    } catch {
+      case NonFatal(_) => Option.empty
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:214]: No logging?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 12]
```diff
@@ -154,4 +183,26 @@ object AsyncDnsResolver {
...
+    }
+
+  private[io] case class CurrentRequest(client: ActorRef,
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala]: final

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala [hunk 13]
```diff
@@ -99,4 +101,43 @@ class AsyncDnsResolverSpec extends AkkaSpec(
...
+        """.stripMargin.getBytes
+      )
+      AsyncDnsResolver.parseSystemNameServers(resolvConf) should be(Some(List.empty))
+    }
+
+    "return nothing when there is no resolv.conf" in {
+      val resolvConf = new File("something-somewhere")
+      AsyncDnsResolver.parseSystemNameServers(resolvConf) should be(None)
+    }
+  }
```
Comment (viktorklang) [inline src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: What about a test case for when the resolv.conf is not properly formatted?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 14]
```diff
@@ -154,4 +183,26 @@ object AsyncDnsResolver {
...
   private[io] def isSrv(name: String) =
     name.nonEmpty && name(0) == '_'
+
+  private[io] val NameserverLine = """^\s*nameserver\s+(.*)$""".r
+
+  def parseSystemNameServers(resolvConf: File): Option[immutable.Seq[InetSocketAddress]] =
+    try {
+      val addresses =
+        for {
+          line <- Source.fromFile(resolvConf).getLines()
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:209]: What character encoding?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 15]
```diff
@@ -154,4 +183,26 @@ object AsyncDnsResolver {
 
   private[io] def isSrv(name: String) =
     name.nonEmpty && name(0) == '_'
+
+  private[io] val NameserverLine = """^\s*nameserver\s+(.*)$""".r
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:200]: Is this regex taken from somewhere and if so, where?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 16]
```diff
@@ -9,32 +11,35 @@ import ru.smslv.akka.dns.raw.{AAAARecord, ARecord, Answer, CNAMERecord, DnsClien
...
-                                  srv: Option[immutable.Seq[SRVRecord]],
-                                  ttl: Long)
+import scala.util.control.NonFatal
 
 class AsyncDnsResolver(cache: SimpleDnsCache, config: Config) extends Actor with ActorLogging {
 
   import AsyncDnsResolver._
 
-  private val nameServers: immutable.Seq[InetSocketAddress] = config.getStringList("nameservers").map(parseNameserverAddress)(breakOut)
+  private val systemNameServers =
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:23]: :) `Option(config.getBoolean("resolv-conf")) collect { case true => parseSystemNameServers(Paths.get("/etc/resolv.conf").toFile) }`

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: And why a Tuple2 + a Boxed Short? A `final case class CacheEntry(id: Short, request: CurrentRequest)` would not only be more efficient in storage, but also have less indirection. And using a Vector would have better locality than pointerchasing in List. :)

File: src/main/resources/reference.conf (hunk 2 above)
Comment (ilya-epifanov) [reply src/main/resources/reference.conf:36]: While I haven't seen it anywhere else, I think it might be useful for testing.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 4 above)
Comment (ilya-epifanov) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Don't think so.
I can think of several options of how to address this:
1. make `requests` a multimap and pick the "most plausible request" for a given reply. I don't like  the "most plausible request" thing, but I feel it should be pretty safe.
2. wait until there are available request slots. This isn't as bad as it sounds, you still need to have 32768 concurrent dns requests to achieve that.
3. In addition to 2., request ids should be per nameserver. I like this option, because I have a gut feeling that no DNS server software is designed to maintain more than 2^16 UDP requests from a single IP
4. In addition to 2. or 3. we might need a TCP DNS implementation.

File: src/main/resources/reference.conf (hunk 2 above)
Comment (huntc) [reply src/main/resources/reference.conf:36]: Testing is largely already supported (see the test). /etc/resolve.conf has its own man page, show me an example where it lives elsewhere. :-)

File: src/main/resources/reference.conf (hunk 3 above)
Comment (huntc) [reply src/main/resources/reference.conf:41]: Sure, why not?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (ilya-epifanov) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: I don't think we should give up near-constant access time here, even if it's slower than linear on average

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 4 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Why worry at all about clashing from a practical level? Nothing is guaranteed with UDP anyhow? Wdyt about just bumping a short and dealing with overflow ?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 15 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:200]: I invented the regex. Note that the corresponding rfc doesn't actually dictate the format of this field, just the keywords and their meanings.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 14 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: OS specific. No encoding is specified by the rfc as I recall. Happy to be corrected though.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: You mean a Seq vs a Map? It is a trade off. We must still scan to remove expired entries - a very real issue given that there witnessed memory retention issues. I'm also careful re the position of elements in the sequence. Oldest requests are first with replies shifted to the front.

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala (hunk 13 above)
Comment (huntc) [reply src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: I would say that's already covered as in the regex won't match. I could include a bad Inet address...

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: @viktorklang I considered `List` over `Vector` here given the scans required in order to filter out expired elements. My understanding is that `List` will offer better performance in that respect. Also, there are a number of operations that work toward the head, and so I intuitively chose `List` given its performance characteristics in this regard. WDYT?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 16 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:23]: Nice, but introducing an option just to lift it for collection feels like something my inner-Klang would avoid. ;-)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 1 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: @viktorklang  Regarding tuples, tuples felt like the intuitive thing to do. I could certainly introduce a case class for the request entries, but are you stating that tuples are to be avoided?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 9 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Actually, that should be:

``` scala
           val ttl = rrsMinTtl.fold(currentTtl)(math.min(currentTtl, _))
```

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 10 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:171]: I prefer to repeat than offer a new layer of abstraction.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 6 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: I understand that using `ThreadLocalRandom` is better given that it is non-synchronized. Given that they'll be no contention as we're within an actor then we don't need to manage contention. I shall thus use `java.util.concurrent.ThreadLocalRandom`. Thanks.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 4 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: I've just trawled through some RFCs and I can't find any guidance on the use of IDs. I'm going to make a change such that we just increment a short value.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 5 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Done

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 7 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Done

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 8 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Possibly, although that's then introducing 3 new constants and degrading readability. I'd prefer not to.

Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Will use `Nil` though.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 11 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:214]: I now log if no resolvers can be determined at all:

``` scala
  if (resolvers.isEmpty) 
    log.warning("No DNS resolvers can be determined, either because of malformed configuration or perhaps an invalid /etc/resolv.conf if that's being used. Do not expect DNS names to be resolved.")
```

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 12 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala]: Done

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala (hunk 13 above)
Comment (huntc) [reply src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: Added another test that provides no address.

**Comment by huntc** [comment]
Test failing to the lack of 2.12 dependencies.

File: src/main/resources/reference.conf (hunk 2 above)
Comment (viktorklang) [reply src/main/resources/reference.conf:36]: I prefer not to make assumptions :)

File: src/main/resources/reference.conf (hunk 3 above)
Comment (viktorklang) [reply src/main/resources/reference.conf:41]: Perhaps mention that in the documentation, and what the behavior is :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 16 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:23]: That argument I don't buy, however, it won't compile since parseSystemNameServers returns an option in-and-of itself. :) (which is an argument I'd buy ) :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 17]
```diff
@@ -1,78 +1,103 @@
...
   private val negativeTtl = config.getDuration("negative-ttl", TimeUnit.MILLISECONDS)
   private val minPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
   private val maxPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
-
-  private val random = new Random()
+  private val requestTtl = FiniteDuration(config.getDuration("request-ttl", TimeUnit.MILLISECONDS), TimeUnit.MILLISECONDS)
 
   private var requestId: Short = 0
-  private val requests = mutable.OpenHashMap[Short, CurrentRequest]()
+  private var requests = List.empty[(Short, CurrentRequest)]
```
Comment (viktorklang) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:41]: Why List iso Vector?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 10 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:171]: Preference is not an argument. :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 15 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:200]: That'd be an excellent comment to this regex :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 14 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: Gah! Can't find any info on this. That's pretty sloppy of the rfc writers. :D

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala (hunk 13 above)
Comment (viktorklang) [reply src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: So you get no feedback if you have a typo in the resolve.conf? (if it doesn't match the regex)

File: src/main/resources/reference.conf (hunk 2 above)
Comment (huntc) [reply src/main/resources/reference.conf:36]: We're always making assumptions in code. I think that this is a reasonable one.

File: src/main/resources/reference.conf (hunk 3 above)
Comment (huntc) [reply src/main/resources/reference.conf:41]: Could you have a go at re-wording my comment (which is doc)? ...or are you referring to some other doc?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 16 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:23]: OK, I'll go with that argument then. ;-)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 10 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:171]: Again, preferences live in code all of the time. This particular preference is one I've adopted for some years, and avoids introducing new abstractions. There are others: http://frozenfractal.com/blog/2016/2/19/sry-sometimes-repeat-yourself/

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 15 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:200]: Wilco.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 14 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: ok, then I believe it is best left as-is - I shall introduce a comment to this extent.

Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: Actually, its a man page: http://man7.org/linux/man-pages/man5/resolv.conf.5.html

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala (hunk 13 above)
Comment (huntc) [reply src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: Correct. We don't actually validate resolv.conf files... I don't really want to introduce a parser here. We just ensure that we extract it correctly. However we now have a log message if no resolvers can be found. I shall additionally include a message indicating the resolvers that can be found:

```
[INFO] [10/20/2016 19:43:50.703] [AsyncDnsResolverSpec-akka.actor.default-dispatcher-5] [akka://AsyncDnsResolverSpec/system/IO-DNS/async-dns/$a] Using the following DNS nameservers: /8.8.8.8:53, /8.8.4.4:53
```

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 17 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:41]: Added now as a comment:

```
  // A List is used over Vector here given the scans required in order to filter out expired elements.
```

File: src/main/resources/reference.conf (hunk 2 above)
Comment (viktorklang) [reply src/main/resources/reference.conf:36]: If resolve-conf = on overrides the use of nameservers, then I think logging an info that resolve-conf is being used instead of "nameservers = […]" might be a good thing so people don't expect both to be used?

File: src/main/resources/reference.conf (hunk 3 above)
Comment (viktorklang) [reply src/main/resources/reference.conf:41]: I mean the doc for the config parameter (line 38-39 above)
I don't know what the intended semantics is for when `request-ttl = 0s` so I can't add that for you. :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 16 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:23]: :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 10 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:171]: But filterNot is an abstraction over fold, why not use fold then?

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 14 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: Still no mention of charset :)

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 11 above)
Comment (viktorklang) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:214]: @huntc CAn't we give a more precise waring if nameservers are empty and resolve-conf is off?

File: src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala (hunk 13 above)
Comment (viktorklang) [reply src/test/scala/ru/smslv/akka/dns/AsyncDnsResolverSpec.scala:167]: :+1:

File: src/main/resources/reference.conf (hunk 2 above)
Comment (huntc) [reply src/main/resources/reference.conf:36]: Sorry @viktorklang - your request is reasonable, but I'm a little out of time on this. Would you mind if this became a separate ticket?

File: src/main/resources/reference.conf (hunk 3 above)
Comment (huntc) [reply src/main/resources/reference.conf:41]: I've enhanced the doc:

```
        # The time that a request is allowed to live before being discarded
        # given no reply. The lower bound of this should always be the amount
        # of time to reasonably expect a DNS server to reply within.
```

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 10 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:171]: Sorry, I'm not getting you. I need to move this along though.

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 14 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:209]: Enhanced:

```
  // OS specific. No encoding or charset is specified by the man page as I recall.
  // See http://man7.org/linux/man-pages/man5/resolv.conf.5.html.
```

File: src/main/scala/akka/io/AsyncDnsResolver.scala (hunk 11 above)
Comment (huntc) [reply src/main/scala/akka/io/AsyncDnsResolver.scala:214]: Yes, possible, just a bit out of time. Would you mind raising a separate ticket if this troubles you?

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 18]
```diff
@@ -1,78 +1,109 @@
...
-      if (resolveIpv4) {
-        resolvers(random.nextInt(resolvers.length)) ! Question4(id, caseFoldedName)
-      }
-      if (resolveIpv6) {
-        resolvers(random.nextInt(resolvers.length)) ! Question6((id | 1).toShort, caseFoldedName)
+      cache.cached(caseFoldedName) match {
+        case Some(answer) =>
+          sender() ! answer
+        case None if isInetAddress(name) =>
+          sender() ! Dns.Resolved(name, immutable.Seq(InetAddress.getByName(name)))
```
Comment (huntc) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:87]: Note that the above code is new - there was a bug previously where internet addresses were forwarded on to the resolver. That's not how the existing Akka DNS resolver behaves (it just validates and then returns them).

File: src/main/scala/akka/io/AsyncDnsResolver.scala [hunk 19]
```diff
@@ -149,9 +182,42 @@ object AsyncDnsResolver {
...
   }
 
   private[io] def isSrv(name: String) =
     name.nonEmpty && name(0) == '_'
+
+  private val ipv4Address = """^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$""".r
+
+  private[io] def isInetAddress(name: String): Boolean =
+    (name.contains(":") && !name.contains(".")) || ipv4Address.findAllMatchIn(name).nonEmpty
+
```
Comment (huntc) [inline src/main/scala/akka/io/AsyncDnsResolver.scala:196]: New code: quick and dirty (but should be reliable) check for whether an address is IPv4 or IPv6.

**Comment by huntc** [comment]
Hi @ilya-epifanov - I've now tested this as part of our ConductR orchestration engine, and I'm happy enough with it as something we can move forward with for Akka's own DNS lookup requirements (when used by ConductR), and for DNS SRV lookups. All now appears to be working fine and I've tested it in a DC/OS environment over the past few days.

Could I get you to make a final release at your earliest convenience? I do not anticipate further testing on my part. Thanks for kicking this project off.

**Comment by ilya-epifanov** [comment]
@huntc Thank you! Sorry for late replies, I am very busy at work lately. I hope @viktorklang will raise tickets for all the best practices breached here:) Initially this was a less-than-a-week project, I didn't strive for beautiful code, so I believe every suggestion by you or @viktorklang is worth implementing.
I'm merging it for now, but just in case you should have merge permissions too.

Again, thank you!

**Comment by huntc** [comment]
Indeed thank you for kicking this project off. I was actually attracted to it because I thought that the code presented well!

Thanks for the commit rights also.

Do we have a new release version? 

The project should get a good workout given our product. It'd be great to see a community develop around it. 

Cheers!

**Comment by ilya-epifanov** [comment]
Thank you!

Sure, I've published a new version `2.4.2-M1`, if you're sure everything works I will promote it to 2.4.2.
